config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "users/registrations" }

  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
    resources :reviews, only: [:destroy]
  end

  resources :venues

  resources :venues, only: [:show] do
    resources :reviews, only: [:index, :new, :create]
  end

  root 'venues#index'

end

app/models/review.rb
class Review < ActiveRecord::Base
  validates :venue_rating, presence: true, numericality: { greater_than: 0, less_than: 6, only_integer: true }, allow_nil: false
  validates :description, presence: true, length: { minimum: 60, maximum: 600}, allow_nil: false
  validates :user_id, presence: true, allow_nil: false, allow_blank: false
  validates :venue_id, presence: true, allow_nil: false, allow_blank: false
  validates :user, presence: true
  validates :venue, presence: true

  belongs_to :user
  belongs_to :venue

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :fname, presence: true
  validates :lname, presence: true
  validates :email, presence: true, allow_nil: false, format: { with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i }

  mount_uploader :profile_photo, ProfilePhotoUploader


  has_many :venues
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def fullname
    return self.fname + ' ' + self.lname
  end

  def admin?
    role == "admin"
  end
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  include PgSearch
  pg_search_scope :search_by_vname_or_address, against: [:vname, :streetnumber, :streetname], using: { tsearch: { prefix: true} }

  NEIGHBORHOODS = [ "Allston", "Back Bay","Beacon Hill", "Brighton", "Brookline", "Cambridge", "Chinatown",
      "Dorchester", "East Boston", "Financial District", "Jamaica Plain", "Mattapan", "North End", "Roxbury", "Seaport", "Somerville", "South Boston", "South End", "Waterfront"]

  validates :user_id, presence: true, allow_nil: false, allow_blank: false
  validates :vname, presence: true, uniqueness: {message: "Business already exists!" }, allow_nil: false, allow_blank: false
  validates :price, presence: true, numericality: { greater_than: 0, less_than: 5, only_integer: true }, allow_nil: false
  validates :cover, presence: true, allow_nil: false, allow_blank: false, inclusion: { in: [true, false] }
  validates :streetnumber, presence: true, numericality: { greater_than: 0, only_integer: true }, allow_nil: false, allow_blank: false
  validates :streetname, presence: true, length: { minimum: 5 }, allow_nil: false, allow_blank: false, format: { with: /\A[a-zA-Z ]+\z/ }
  validates :vtype, presence: true, allow_nil: false, allow_blank: false, inclusion: { in: ["Bar", "Club"] }
  validates :neighborhood, presence: true, allow_nil: false, allow_blank: false, inclusion: {in: NEIGHBORHOODS }
  validates :user, presence: true

  has_many :reviews
  belongs_to :user
  def address
    return "#{self.streetnumber} #{self.streetname.strip}"
  end
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController

  def destroy
    review_id = params[:id]
    @review = Review.find(review_id)
    @user = @review.user
    @review.delete

    redirect_to admin_user_path(@user.id), notice: "Review for #{@user.username} has been deleted."
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users = User.all.order(role: :asc, fname: :asc)
    @reviews = Review.all
  end

  def destroy
    user_id = params[:id]
    @user = User.find(user_id)
    @reviews = @user.reviews
    @reviews.delete_all
    @user.delete
    redirect_to admin_users_path, notice: "You have successfully deleted a user and their reviews"
  end

  def show
    user_id = params[:id]
    @user = User.find(user_id)
    @reviews = @user.reviews
    @venues = @user.venues

    render :show
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

   protected

   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:fname, :lname, :username, :profile_photo])
   end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :authenticate_user!
  def create
    @review = Review.new(review_params)
    @review.user = current_user
    @review.venue_id = params[:venue_id]

    if @review.save
      ReviewMailer.new_review(@review).deliver_later
      redirect_to venue_path(Venue.find(@review.venue_id))
    else
      redirect_to venue_path(Venue.find(@review.venue_id)), notice: "Review submission was not valid"

    end
  end


  def review_params
     params.require(:review).permit(:venue_rating, :description)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    # Override the action you want here.
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/venue_controller.rb
class VenueController < ApplicationController
  def index
    @venues = Venue.all
  end

  def show

  end

  def update

  end

  def destroy

  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index]

  NEIGHBORHOODS = [ "North End", "Waterfront","Financial District", "Back Bay",
    "Beacon Hill", "Chinatown", "Seaport", "South End", "Roxbury", "Dorchester", "Mattapan", "East Boston", "South Boston", "Jamaica Plain", "Allston", "Brighton", "Brookline", "Cambridge", "Somerville"]

  def index
    @venues = Venue.all
  end

  def show
    @venue = Venue.find(params[:id])
    @reviews = @venue.reviews.order(created_at: :desc)
    @review = Review.new
  end

  def edit
    venue_id = params[:id]
    @venue = Venue.find(venue_id)
    @neighborhoods = NEIGHBORHOODS.sort
    @method = "patch"
    @url = venue_path
    @label = "Update Business"

    render :edit
  end

  def new
    if current_user != nil
      @venue = Venue.new
      @neighborhoods = NEIGHBORHOODS.sort
      @method = "post"
      @url = venues_path
      @label = "Add Business"
    else
      render :index
    end
  end

  def create
    @venue = Venue.new(venue_params)
    @venue.user = current_user

    if @venue.save
      redirect_to venue_path(@venue.id)
    else
      @neighborhoods = NEIGHBORHOODS.sort
      render :new
    end
  end

  def update
    venue_id = params[:id]
    @venue = Venue.find(venue_id)


    if @venue.update(venue_params)
      redirect_to venue_path(@venue.id), notice: "Admin successfully updated page"
    else
      @neighborhood = NEIGHBORHOODS.sort
      render :edit
    end
  end

  def destroy

  end


  def venue_params
    params.require(:venue).permit(:vname, :price, :cover, :streetnumber, :streetname, :vtype, :neighborhood)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/venue_helper.rb
module VenueHelper
end

app/views/admin/users/index.html.erb
<h2>Admin Access</h2>

<table>
  <tr>
    <th>Username</th>
    <th>Full Name</th>
    <th>Role</th>
    <th>Email</th>
    <th>Joined</th>
    <th></th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.username,admin_user_path(user.id), method: :get %></td>
      <td><%= user.fullname %></td>
      <td><%= user.role.capitalize %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.strftime("%D") %></td>
      <% if user == current_user %>
        <td></td>
      <% else %>
        <td><%= button_to 'Delete', admin_user_path(user.id), id: "delete-#{user.username}", method: :delete %></td>
      <% end %>
    </tr>
  <% end %>

</table>

app/views/admin/users/show.html.erb
<h1><%= @user.fullname %></h1>

<ul>
  <li><b>Username:</b> <%= @user.username %></li>
  <li><b>Email:</b> <%= @user.email %></li>
  <li><b>Role:</b> <%= @user.role.capitalize %></li>
  <li><b>Date Joined:</b> <%= @user.created_at.strftime("%D") %></li>
</ul>

<h2>Bar/Club Submissions</h2>
<% if @venues.empty? == false %>
  <table>
    <tr>
      <th>Date Added</th>
      <th>Name</th>
      <th>Address</th>
      <th>Type</th>
      <th>Neighborhood</th>
      <th></th>
      <th></th>
    </tr>
    <% @venues.each do |venue| %>
      <td><%= venue.created_at.strftime("%D") %></td>
      <td><%= venue.vname %></td>
      <td><%= venue.address %></td>
      <td><%= venue.vtype %></td>
      <td><%= venue.neighborhood %></td>
      <td><%= button_to "Edit", edit_venue_path(venue.id), method: :get %></td>
      <td><%= button_to "Delete", venue_path(venue.id), method: :delete %></td>
    <% end %>
  </table>

<% else %>
  <p>User has no Bar/Club Submissions</p>
<% end %>


<h2>Reviews</h2>
<% if @reviews.empty? == false %>
  <table>
    <tr>
      <th>Date Added</th>
      <th>Venue</th>
      <th>Rating</th>
      <th>Description</th>
      <th></th>
    </tr>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.created_at.strftime("%D") %></td>
        <td><%= review.venue.vname %></td>
        <td><%= review.venue_rating %></td>
        <td><%= review.description %></td>
        <td><%= button_to "Delete", admin_review_path(review.id), method: :delete %></td>
      </tr>

    <% end %>
  </table>
<% else %>
  <p>User has no reviews</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Boston Nightlife Review</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<nav>
  <ul class="menu align-right">
    <% if user_signed_in? %>
      <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
      <li><img src="<%= current_user.profile_photo %>" alt="profile picture" height="42" width="42"/> <%= link_to "Account", edit_user_registration_path(current_user.id) %></li>
      <% if current_user.admin? %>
        <li><%= link_to 'Admin Access', admin_users_path %></li>
      <% end %>
    <% else %>
      <li><%= link_to 'Sign In', new_user_session_path %></li>
      <li><%= link_to 'Sign Up', new_user_registration_path %></li>
    <% end %>
  </ul>
</nav>
<%= yield %>

</body>
</html>

app/views/venues/_review_form.html.erb
<%= simple_form_for (@review), method: "post", url: venue_reviews_path(@venue.id) do |f| %>
  <%= f.label :venue_rating,label: "Rating" %>
  <%= f.collection_radio_buttons :venue_rating, [[1, '*'], [2, '**'], [3, '***'], [4, '****'], [5, '*****']], :first, :last %> <br>
  <%= f.input :description, as: :text %>

  <%= f.button :submit, "Add a Review" %>
<% end %>

app/views/venues/_venue_form.html.erb
<%= simple_form_for (@venue), method: @method , url: @url do |f| %>
  <%= f.input :vname, label: "Name" %>
  <%= f.input :streetnumber, label: "Street Number" %>
  <%= f.input :streetname, label: "Street Name" %>
  <%= f.label :neighborhood, label: "Neighborhood" %>
  <%= f.select(:neighborhood, @neighborhoods.map { |value| [ value, value ] }, include_blank: false)  %> <br>
  <%= f.label :vtype, label: "Bar or Club?" %>
  <%= f.select(:vtype, [['Bar', 'Bar'], ['Club', 'Club']]) %> <br>
  <%= f.label :price, label: "Price" %>
  <%= f.select(:price, [['$', 1], ['$$', 2],['$$$', 3],['$$$$', 4]]) %> <br>
  <%= f.label :cover, label: "Cover" %>
  <%= f.collection_radio_buttons :cover, [[true, 'Yes'], [false, 'No']], :first, :last %> <br>


  <%= f.button :submit, @label %>
<% end %>

app/views/venues/edit.html.erb
<h1>Edit Business</h1>

 <%= render 'venue_form', locals: {venue: @venue, neighborhood: @neighborhood, method: @method , url: @url, label: @label } %>

app/views/venues/index.html.erb
<h2>Nightlife in Boston</h2>
<% if user_signed_in? %>
  <%= button_to "Add Bar or Club", new_venue_path, id: "new-venue-btn", method: :get %>
<% end %>
<% @venues.each do |venue| %>
  <div class="venue">
    <%= link_to venue.vname, venue_path(venue.id) %>
  </div>
<% end %>

app/views/venues/new.html.erb
<h1>Add New Business</h1>

<%= render 'venue_form' %>

app/views/venues/show.html.erb
<h2><%= @venue.vname %></h2>

<ul>
  <li>Address: <%= @venue.address %></li>
  <li>Neighborhood:  <%= @venue.neighborhood %></li>
  <% if @venue.price == 4 %>
    <li>Price: $$$$</li>
  <% elsif @venue.price == 3 %>
    <li>Price: $$$</li>
  <% elsif @venue.price == 2 %>
    <li>Price: $$</li>
  <% else %>
    <li>Price: $</li>
  <% end %>
  <% if @venue.cover == true %>
    <li>Cover: Yes</li>
  <% else %>
    <li>Cover: No</li>
  <% end %>
</ul>
<%= render 'review_form' %>
<br>
<br>

<% if @reviews != nil || @reviews.empty? == false %>
  <% @reviews.each do |review| %>
    <div class="review">
        <%= review.user.username %>
        <% d = review.created_at %>
        <%= d.strftime("%D") %><br>

        Rating: <%= review.venue_rating.to_i %>
        <p><%= review.description %></p>
    </div>
  <% end %>
<% end  %>